Repository AY2122S2-CS2103-F09-4/tp, pull requests merged in 2022-03, with the labels that each got.

#49 Update readme
  README.md
  docs/UserGuide.md
  docs/team/darshan152.md
  docs/team/onefangg.md
Labels: documentation

#81 Update DeveloperGuide.md
  docs/DeveloperGuide.md
Labels: documentation

#86 Update UserGuide.md
  docs/UserGuide.md
Labels: documentation

#111 Update UI aesthetics
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListPanel.fxml
  src/main/resources/view/ReadyBakeyTheme.css
  src/main/resources/view/ResultDisplay.fxml
Labels: enhancement

#120 Fix bug in UI
  src/main/resources/view/Extensions.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ReadyBakeyTheme.css
Labels: bug

#136 Update Developer Guide for AddOrderCommand
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/AddOrderSequenceDiagram.puml
  docs/images/AddOrderSequenceDiagram.png
  src/main/java/seedu/address/logic/commands/AddOrderCommand.java
  src/main/java/seedu/address/logic/commands/MarkOrderCommand.java
Labels: documentation, type.story

#135 Update DG with FindOrderCommand Implementation
  docs/DeveloperGuide.md
  docs/diagrams/FindOrderSequenceDiagram.puml
  docs/images/FindOrderSequenceDiagram.png
Labels: documentation

#137 Update DeveloperGuide for EditOrderCommand
  docs/DeveloperGuide.md
  docs/diagrams/EditOrderSequenceDiagram.puml
  docs/images/EditOrderSequenceDiagram.png
Labels: documentation

#160 Implement find order command features for additional order attributes
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/FindOrderCollectionTypeCommand.java
  src/main/java/seedu/address/logic/commands/FindOrderCommand.java
  src/main/java/seedu/address/logic/commands/FindOrderDetailsCommand.java
  src/main/java/seedu/address/logic/commands/FindOrderRemarkCommand.java
  src/main/java/seedu/address/logic/parser/FindOrderCommandParser.java
  src/main/java/seedu/address/logic/parser/FindPersonCommandParser.java
  src/main/java/seedu/address/model/order/CollectionTypeContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/order/DetailsContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/order/Order.java
  src/main/java/seedu/address/model/order/RemarkContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/Remark.java
  src/test/java/seedu/address/logic/commands/FindOrderCollectionTypeCommandTest.java
  src/test/java/seedu/address/logic/commands/FindOrderDetailsCommandTest.java
  src/test/java/seedu/address/logic/commands/FindOrderNameCommandTest.java
  src/test/java/seedu/address/logic/commands/FindOrderPhoneCommandTest.java
  src/test/java/seedu/address/logic/commands/FindOrderRemarkCommandTest.java
  src/test/java/seedu/address/testutil/TypicalOrders.java
Labels: enhancement, type.story

#153 Bug null order details
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddOrderCommand.java
  src/main/java/seedu/address/logic/commands/DeletePersonCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/order/Order.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/OrderListPanel.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddOrderCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/ModelStub.java
Labels: bug

#159 Implement some fixes for add order command
  src/main/java/seedu/address/logic/commands/AddOrderCommand.java
  src/main/java/seedu/address/logic/parser/AddOrderCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/order/DeliveryDateTime.java
  src/main/java/seedu/address/model/order/Details.java
  src/main/java/seedu/address/model/order/Order.java
  src/main/java/seedu/address/model/person/Remark.java
  src/test/java/seedu/address/model/order/DeliveryDateTimeTest.java
  src/test/java/seedu/address/model/order/OrderTest.java
  src/test/java/seedu/address/model/person/RemarkTest.java
Labels: bug, enhancement
